name: Publish
on: [push]
jobs:
  mac:
    name: OSX (x64)
    runs-on: macos-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}
      - name: Build Aardium
        run: ./buildnative.sh
        env:
          MAC_CERT_BASE64: ${{ secrets.MAC_CERT_BASE64 }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          MAC_DEV_PASSWORD: ${{ secrets.MAC_DEV_PASSWORD }}
      - name: Upload Aardium
        uses: actions/upload-artifact@v2
        with:
          name: mac
          path: Aardium/dist/Aardium-Darwin-arm64.tar.gz