name: Publish
on: [push]
jobs:
  mac_arm64:
    name: OSX (arm64)
    runs-on: macos-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}
      - name: Build Aardium
        run: ./buildnative.sh arm64
        env:
          MAC_CERT_BASE64: ${{ secrets.MAC_CERT_BASE64 }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          MAC_DEV_PASSWORD: ${{ secrets.MAC_DEV_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Aardium
        uses: actions/upload-artifact@v2
        with:
          name: mac_arm64
          path: Aardium/dist/Aardium-Darwin-arm64.tar.gz
  mac_x64:
    name: OSX (x64)
    runs-on: macos-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Add Cert to Keychain
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.MAC_CERT_BASE64 }}
          p12-password: ${{ secrets.MAC_CERT_PASSWORD }}
      - name: Build Aardium
        run: ./buildnative.sh x86_64
        env:
          MAC_CERT_BASE64: ${{ secrets.MAC_CERT_BASE64 }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          MAC_DEV_PASSWORD: ${{ secrets.MAC_DEV_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Aardium
        uses: actions/upload-artifact@v2
        with:
          name: mac_x64
          path: Aardium/dist/Aardium-Darwin-x64.tar.gz
  linux_x64:
    name: Linux (x64)
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Build Aardium
        run: ./buildnative.sh
      - name: Upload Aardium
        uses: actions/upload-artifact@v2
        with:
          name: linux_x64
          path: Aardium/dist/Aardium-Linux-x64.tar.gz